# Generated by Django 4.2.4 on 2023-09-17 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('travel_id', models.AutoField(primary_key=True, serialize=False)),
                ('travel_departing', models.DateField(blank=True, max_length=60, null=True)),
                ('travel_returing', models.DateField(blank=True, max_length=60, null=True)),
                ('travel_adults', models.IntegerField(blank=True, null=True)),
                ('travel_children', models.IntegerField(blank=True, null=True)),
                ('travel_class', models.CharField(blank=True, max_length=60, null=True)),
            ],
        ),
    ]
