# Generated by Django 4.2.4 on 2023-09-17 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brhindApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='travel_method',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
