# Generated by Django 4.2.4 on 2023-09-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brhindApp', '0002_booking_travel_method'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='travel_class',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='travel_method',
        ),
        migrations.AddField(
            model_name='booking',
            name='travel_business',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='travel_economy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='travel_oneway',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='travel_roundtrip',
            field=models.BooleanField(default=False),
        ),
    ]
