# Generated by Django 4.2.4 on 2023-09-17 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brhindApp', '0003_remove_booking_travel_class_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='travel_business',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='travel_economy',
        ),
        migrations.AddField(
            model_name='booking',
            name='travel_class',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
