# Generated by Django 4.2.4 on 2023-09-18 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brhindApp', '0004_remove_booking_travel_business_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='travel_oneway',
        ),
    ]
