# Generated by Django 4.2.4 on 2023-09-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brhindApp', '0005_remove_booking_travel_oneway'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='travel_oneway',
            field=models.BooleanField(default=False),
        ),
    ]
