# Generated by Django 4.2.4 on 2023-09-18 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brhindApp', '0006_booking_travel_oneway'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='travel_oneway',
        ),
    ]
