# Generated by Django 4.2.4 on 2023-09-19 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brhindApp', '0009_remove_booking_travel_class'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight',
            old_name='flight_1',
            new_name='country_1',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='flight_2',
            new_name='country_2',
        ),
        migrations.AddField(
            model_name='flight',
            name='flight_number',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='time',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='time_1',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
