# Generated by Django 4.2.4 on 2023-09-19 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brhindApp', '0011_flight_flight_destinacion_flight_flight_destinacion2'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='price2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
