# Generated by Django 4.2.4 on 2023-09-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brhindApp', '0012_flight_price2'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='time2',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='time_3',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
