# Generated by Django 4.2.4 on 2023-09-19 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brhindApp', '0013_flight_time2_flight_time_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='time_travel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brhindApp.booking'),
        ),
    ]
