# Generated by Django 4.2.4 on 2023-09-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brhindApp', '0015_remove_flight_time_travel_booking_time_travel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='time_travel',
        ),
        migrations.AddField(
            model_name='booking',
            name='time_travel',
            field=models.ManyToManyField(to='brhindApp.flight'),
        ),
    ]
