# Generated by Django 4.2.4 on 2023-09-19 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brhindApp', '0016_remove_booking_time_travel_booking_time_travel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='time_travel',
        ),
        migrations.AddField(
            model_name='booking',
            name='time_travel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brhindApp.flight'),
        ),
    ]
