# Generated by Django 4.2.4 on 2023-09-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brhindApp', '0017_remove_booking_time_travel_booking_time_travel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight1',
            fields=[
                ('flight_id', models.AutoField(primary_key=True, serialize=False)),
                ('flight_number', models.CharField(blank=True, max_length=60, null=True)),
                ('flight_destinacion', models.CharField(blank=True, max_length=60, null=True)),
                ('flight_destinacion2', models.CharField(blank=True, max_length=60, null=True)),
                ('country_1', models.CharField(blank=True, max_length=60, null=True)),
                ('country_2', models.CharField(blank=True, max_length=60, null=True)),
                ('time', models.CharField(blank=True, max_length=60, null=True)),
                ('time_1', models.CharField(blank=True, max_length=60, null=True)),
                ('time2', models.CharField(blank=True, max_length=60, null=True)),
                ('time_3', models.CharField(blank=True, max_length=60, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('price2', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='flight',
            name='price2',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='time2',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='time_3',
        ),
    ]
