# Generated by Django 4.2.4 on 2023-09-20 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brhindApp', '0020_booking_paketa_1_booking_paketa_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flight1',
            old_name='country_1',
            new_name='country_3',
        ),
        migrations.RenameField(
            model_name='flight1',
            old_name='country_2',
            new_name='country_4',
        ),
        migrations.RenameField(
            model_name='flight1',
            old_name='flight_destinacion',
            new_name='flight_destinacion3',
        ),
        migrations.RenameField(
            model_name='flight1',
            old_name='flight_destinacion2',
            new_name='flight_destinacion4',
        ),
        migrations.RenameField(
            model_name='flight1',
            old_name='flight_number',
            new_name='flight_number1',
        ),
    ]
