# Generated by Django 4.2.4 on 2023-09-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brhindApp', '0021_rename_country_1_flight1_country_3_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Flight1',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='time_travel',
        ),
        migrations.AddField(
            model_name='flight',
            name='price2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='time2',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='time_3',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
