# Generated by Django 4.2.4 on 2023-09-23 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brhindApp', '0022_delete_flight1_remove_booking_time_travel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Paketa_1',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='Paketa_2',
        ),
        migrations.AddField(
            model_name='booking',
            name='travel_flight',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brhindApp.flight'),
        ),
    ]
