# Generated by Django 4.2.4 on 2023-09-23 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brhindApp', '0023_remove_booking_paketa_1_remove_booking_paketa_2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flight',
            name='price2',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='time2',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='time_3',
        ),
    ]
