# Generated by Django 4.2.4 on 2023-09-27 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brhindApp', '0024_remove_flight_price2_remove_flight_time2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='price',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
