# Generated by Django 4.2.4 on 2023-09-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brhindApp', '0028_alter_flight_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='ticket_is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
