# Generated by Django 4.2.4 on 2023-10-07 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brhindApp', '0032_alter_flight_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='travel_city',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
