# Generated by Django 4.2.4 on 2023-10-08 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('brhindApp', '0034_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='travel_city',
        ),
        migrations.AddField(
            model_name='booking',
            name='travel_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brhindApp.category'),
        ),
    ]
