# Generated by Django 4.2.4 on 2023-10-09 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brhindApp', '0037_booking_flight_destinacion2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='flight_destinacion2',
        ),
    ]
